# Generated by Django 6.0.2 on 2026-02-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productvariant_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_secondary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_secondary', True)), fields=('product',), name='one_secondary_image_per_product'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.CheckConstraint(condition=models.Q(('is_primary', True), ('is_secondary', True), _negated=True), name='image_not_both_primary_and_secondary'),
        ),
    ]
