# Generated by Django 6.0.2 on 2026-03-05 06:34

import cloudinary.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_productimage_image_url_productimage_image'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productimage',
            name='image_not_both_primary_and_secondary',
        ),
        migrations.AddField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='product_image'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.CheckConstraint(condition=models.Q(('is_primary', True), ('is_secondary', True), _negated=True), name='image_not_primary_and_secondary'),
        ),
    ]
