# Generated by Django 6.0.2 on 2026-02-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='admin', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
