# Generated by Django 6.0.2 on 2026-02-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_created_at_user_phone_number_user_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=8592044236, max_length=15),
            preserve_default=False,
        ),
    ]
