import json
import re

def parse_multipart_data(data):
    """
    Parses a flat multipart form-data dictionary into a nested Python dict, 
    evaluating stringified lists and handling file inputs properly.
    Supports nested arrays like images[0][id].
    """
    parsed_data = {}

    for key, value in data.items():
        
        # Parse value strings
        if isinstance(value, str):
            lower_val = value.lower()
            if lower_val == "true":
                value = True
            elif lower_val == "false":
                value = False
            elif value.startswith("[") or value.startswith("{"):
                try:
                    value = json.loads(value)
                except json.JSONDecodeError:
                    pass
        
        # Check for array notation like images[0][id]
        match = re.match(r"^([a-zA-Z0-9_]+)\[(\d+)\]\[([a-zA-Z0-9_]+)\]$", key)
        if match:
            list_name = match.group(1)
            index = int(match.group(2))
            sub_key = match.group(3)

            if list_name not in parsed_data:
                parsed_data[list_name] = []
            
            # Ensure list is long enough
            while len(parsed_data[list_name]) <= index:
                parsed_data[list_name].append({})
            
            parsed_data[list_name][index][sub_key] = value
        else:
            parsed_data[key] = value

    # Filter out empty dictionaries generated by skipped indexes
    for key, value in parsed_data.items():
        if isinstance(value, list):
            parsed_data[key] = [item for item in value if item]

    return parsed_data
